[workspace]
authors = ["indexofire <indexofire@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "gside"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
docs = "mkdocs serve"
docs-build = "mkdocs build --strict"

[dependencies]
python = ">=3.11"
blast = ">=2.16"
skani = "0.3.*"
mash = ">=2.3"
mmseqs2 = ">=15"

[pypi-dependencies]
gside = { path = ".", editable = true }

[feature.dev.pypi-dependencies]
mkdocs = ">=1.6"
mkdocs-material = ">=9.0"
mkdocs-static-i18n = ">=1.2"

[environments]
default = { features = [], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
